# Generated by Django 3.1.1 on 2020-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
