# Generated by Django 3.1.1 on 2020-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20201006_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
