# Generated by Django 3.1.1 on 2020-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_magazine_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
