# Generated by Django 3.1.1 on 2020-10-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_auto_20201006_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='price',
        ),
    ]
