# Generated by Django 3.1.1 on 2020-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_remove_portfolio_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
