# Generated by Django 3.1.1 on 2020-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0009_delete_salessummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='magazine',
            name='tags',
            field=models.ManyToManyField(to='magazines.Tag'),
        ),
    ]
