# Generated by Django 3.1.1 on 2020-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0013_post_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
