# Generated by Django 3.1.1 on 2020-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0014_auto_20201102_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='static/images/posts'),
        ),
    ]
