# Generated by Django 3.1.1 on 2020-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0015_auto_20201102_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
