# Generated by Django 3.1.2 on 2020-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0016_post_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='description2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
