# Generated by Django 3.1.1 on 2020-11-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0019_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='purchasecount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magazine',
            name='viewcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
