# Generated by Django 3.1.1 on 2020-11-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0021_magazine_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='tags',
        ),
        migrations.AddField(
            model_name='magazine',
            name='magazineGroup',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
