# Generated by Django 3.1.1 on 2020-11-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0022_auto_20201109_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='magazineGroup',
        ),
        migrations.AddField(
            model_name='magazine',
            name='tags',
            field=models.ManyToManyField(to='magazines.Tag'),
        ),
    ]
