# Generated by Django 3.1.1 on 2020-11-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0024_auto_20201109_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='purchasecount',
        ),
    ]
